using Valve.VR;

namespace FloatSoda.OVR.Exceptions;

// ReSharper disable once InconsistentNaming
public class EVRInitializeException(string message, EVRInitError errorCode) : OVRException<EVRInitError>(message, errorCode);

// ReSharper disable once InconsistentNaming
public class EVRDriverEVRInitializeException(string message, EVRInitError errorCode) : EVRInitializeException(message, errorCode);

// ReSharper disable once InconsistentNaming
public class EVRIPCInitializeException(string message, EVRInitError errorCode) : EVRInitializeException(message, errorCode);

// ReSharper disable once InconsistentNaming
public class EVRCompositorInitializeException(string message, EVRInitError errorCode) : EVRInitializeException(message, errorCode);

// ReSharper disable once InconsistentNaming
public class EVRVendorSpecificInitializeException(string message, EVRInitError errorCode) : EVRInitializeException(message, errorCode);

public static class VrInitialExceptionValidator
{
    public static void ThrowIfError(this EVRInitError error)
    {
        if (error == EVRInitError.None) return;

        throw error switch
        {
            // --- 一般的な初期化エラー ---
            EVRInitError.Unknown => new EVRInitializeException("未知の初期化エラーが発生しました。", error),
            EVRInitError.Init_InstallationNotFound => new EVRInitializeException("OpenVRのインストールが見つかりません。", error),
            EVRInitError.Init_InstallationCorrupt => new EVRInitializeException("OpenVRのインストールが壊れています。", error),
            EVRInitError.Init_VRClientDLLNotFound => new EVRInitializeException("vrclient.dllが見つかりません。", error),
            EVRInitError.Init_FileNotFound => new EVRInitializeException("必要な構成ファイルが見つかりません。", error),
            EVRInitError.Init_FactoryNotFound => new EVRInitializeException("ファクトリインターフェースの取得に失敗しました。", error),
            EVRInitError.Init_InterfaceNotFound => new EVRInitializeException("要求されたインターフェースが見つかりません。", error),
            EVRInitError.Init_InvalidInterface => new EVRInitializeException("インターフェースが無効です。", error),
            EVRInitError.Init_UserConfigDirectoryInvalid => new EVRInitializeException("ユーザー設定ディレクトリが無効です。", error),
            EVRInitError.Init_HmdNotFound => new EVRInitializeException("HMDが見つからないか、接続されていません。", error),
            EVRInitError.Init_NotInitialized => new EVRInitializeException("OpenVRが初期化されていません。", error),
            EVRInitError.Init_PathRegistryNotFound => new EVRInitializeException("パスレジストリが見つかりません。", error),
            EVRInitError.Init_NoConfigPath => new EVRInitializeException("構成パスが設定されていません。", error),
            EVRInitError.Init_NoLogPath => new EVRInitializeException("ログパスが設定されていません。", error),
            EVRInitError.Init_PathRegistryNotWritable => new EVRInitializeException("パスレジストリに書き込めません。", error),
            EVRInitError.Init_AppInfoInitFailed => new EVRInitializeException("アプリケーション情報の初期化に失敗しました。", error),
            EVRInitError.Init_Retry => new EVRInitializeException("再試行が必要です。", error),
            EVRInitError.Init_InitCanceledByUser => new EVRInitializeException("ユーザーによって初期化がキャンセルされました。", error),
            EVRInitError.Init_AnotherAppLaunching => new EVRInitializeException("別のアプリケーションが起動中です。", error),
            EVRInitError.Init_SettingsInitFailed => new EVRInitializeException("設定の初期化に失敗しました。", error),
            EVRInitError.Init_ShuttingDown => new EVRInitializeException("システムが終了処理中です。", error),
            EVRInitError.Init_TooManyObjects => new EVRInitializeException("オブジェクトが多すぎます。", error),
            EVRInitError.Init_NoServerForBackgroundApp => new EVRInitializeException("バックグラウンドアプリ用のサーバーがありません。", error),
            EVRInitError.Init_NotSupportedWithCompositor => new EVRInitializeException("コンポジター使用時はサポートされません。", error),
            EVRInitError.Init_NotAvailableToUtilityApps => new EVRInitializeException("ユーティリティアプリでは利用できません。", error),
            EVRInitError.Init_Internal => new EVRInitializeException("内部エラーが発生しました。", error),
            EVRInitError.Init_HmdDriverIdIsNone => new EVRInitializeException("HMDドライバIDがNoneです。", error),
            EVRInitError.Init_HmdNotFoundPresenceFailed => new EVRInitializeException("HMDの存在確認に失敗しました。", error),
            EVRInitError.Init_VRMonitorNotFound => new EVRInitializeException("VRモニターが見つかりません。", error),
            EVRInitError.Init_VRMonitorStartupFailed => new EVRInitializeException("VRモニターの起動に失敗しました。", error),
            EVRInitError.Init_LowPowerWatchdogNotSupported => new EVRInitializeException("低電力ウォッチドッグはサポートされていません。", error),
            EVRInitError.Init_InvalidApplicationType => new EVRInitializeException("アプリケーションタイプが無効です。", error),
            EVRInitError.Init_NotAvailableToWatchdogApps => new EVRInitializeException("ウォッチドッグアプリでは利用できません。", error),
            EVRInitError.Init_WatchdogDisabledInSettings => new EVRInitializeException("設定でウォッチドッグが無効になっています。", error),
            EVRInitError.Init_VRDashboardNotFound => new EVRInitializeException("VRダッシュボードが見つかりません。", error),
            EVRInitError.Init_VRDashboardStartupFailed => new EVRInitializeException("VRダッシュボードの起動に失敗しました。", error),
            EVRInitError.Init_VRHomeNotFound => new EVRInitializeException("VR Homeが見つかりません。", error),
            EVRInitError.Init_VRHomeStartupFailed => new EVRInitializeException("VR Homeの起動に失敗しました。", error),
            EVRInitError.Init_RebootingBusy => new EVRInitializeException("再起動処理中のためビジーです。", error),
            EVRInitError.Init_FirmwareUpdateBusy => new EVRInitializeException("ファームウェア更新中のためビジーです。", error),
            EVRInitError.Init_FirmwareRecoveryBusy => new EVRInitializeException("ファームウェア復旧中のためビジーです。", error),
            EVRInitError.Init_USBServiceBusy => new EVRInitializeException("USBサービスがビジーです。", error),
            EVRInitError.Init_VRWebHelperStartupFailed => new EVRInitializeException("VR Web Helperの起動に失敗しました。", error),
            EVRInitError.Init_TrackerManagerInitFailed => new EVRInitializeException("トラッカーマネージャーの初期化に失敗しました。", error),
            EVRInitError.Init_AlreadyRunning => new EVRInitializeException("既に実行中です。", error),
            EVRInitError.Init_FailedForVrMonitor => new EVRInitializeException("VRモニター用プロセスの初期化に失敗しました。", error),
            EVRInitError.Init_PropertyManagerInitFailed => new EVRInitializeException("プロパティマネージャーの初期化に失敗しました。", error),
            EVRInitError.Init_WebServerFailed => new EVRInitializeException("Webサーバーの起動に失敗しました。", error),
            EVRInitError.Init_IllegalTypeTransition => new EVRInitializeException("不正なタイプ遷移です。", error),
            EVRInitError.Init_MismatchedRuntimes => new EVRInitializeException("ランタイムのバージョンが一致しません。", error),
            EVRInitError.Init_InvalidProcessId => new EVRInitializeException("プロセスIDが無効です。", error),
            EVRInitError.Init_VRServiceStartupFailed => new EVRInitializeException("VRサービスの起動に失敗しました。", error),
            EVRInitError.Init_PrismNeedsNewDrivers => new EVRInitializeException("Prismドライバの更新が必要です。", error),
            EVRInitError.Init_PrismStartupTimedOut => new EVRInitializeException("Prismの起動がタイムアウトしました。", error),
            EVRInitError.Init_CouldNotStartPrism => new EVRInitializeException("Prismを起動できませんでした。", error),
            EVRInitError.Init_CreateDriverDirectDeviceFailed => new EVRInitializeException("ドライバダイレクトデバイスの作成に失敗しました。", error),
            EVRInitError.Init_PrismExitedUnexpectedly => new EVRInitializeException("Prismが予期せず終了しました。", error),

            // --- ドライバ関連 ---
            EVRInitError.Driver_Failed => new EVRDriverEVRInitializeException("ドライバのエラーです。", error),
            EVRInitError.Driver_Unknown => new EVRDriverEVRInitializeException("未知のドライバエラーです。", error),
            EVRInitError.Driver_HmdUnknown => new EVRDriverEVRInitializeException("未知のHMDドライバです。", error),
            EVRInitError.Driver_NotLoaded => new EVRDriverEVRInitializeException("ドライバがロードされていません。", error),
            EVRInitError.Driver_RuntimeOutOfDate => new EVRDriverEVRInitializeException("ドライバのランタイムが古すぎます。", error),
            EVRInitError.Driver_HmdInUse => new EVRDriverEVRInitializeException("HMDが別のプロセスで使用中です。", error),
            EVRInitError.Driver_NotCalibrated => new EVRDriverEVRInitializeException("ドライバが校正されていません。", error),
            EVRInitError.Driver_CalibrationInvalid => new EVRDriverEVRInitializeException("ドライバの校正データが無効です。", error),
            EVRInitError.Driver_HmdDisplayNotFound => new EVRDriverEVRInitializeException("HMDのディスプレイが見つかりません。", error),
            EVRInitError.Driver_TrackedDeviceInterfaceUnknown => new EVRDriverEVRInitializeException("トラッキングデバイスインターフェースが不明です。", error),
            EVRInitError.Driver_HmdDriverIdOutOfBounds => new EVRDriverEVRInitializeException("HMDドライバIDが範囲外です。", error),
            EVRInitError.Driver_HmdDisplayMirrored => new EVRDriverEVRInitializeException("HMDディスプレイがミラーリング設定になっています。", error),
            EVRInitError.Driver_HmdDisplayNotFoundLaptop => new EVRDriverEVRInitializeException("ラップトップ用HMDディスプレイが見つかりません。", error),

            // --- IPC (プロセス間通信) 関連 ---
            EVRInitError.IPC_ServerInitFailed => new EVRIPCInitializeException("IPCサーバーの初期化に失敗しました。", error),
            EVRInitError.IPC_ConnectFailed => new EVRIPCInitializeException("IPC接続に失敗しました。", error),
            EVRInitError.IPC_SharedStateInitFailed => new EVRIPCInitializeException("共有ステートの初期化に失敗しました。", error),
            EVRInitError.IPC_CompositorInitFailed => new EVRIPCInitializeException("コンポジターの初期化に失敗しました。", error),
            EVRInitError.IPC_MutexInitFailed => new EVRIPCInitializeException("Mutexの初期化に失敗しました。", error),
            EVRInitError.IPC_Failed => new EVRIPCInitializeException("IPC接続エラーが発生しました。", error),
            EVRInitError.IPC_CompositorConnectFailed => new EVRIPCInitializeException("コンポジターへの接続に失敗しました。", error),
            EVRInitError.IPC_CompositorInvalidConnectResponse => new EVRIPCInitializeException("コンポジターからの接続レスポンスが無効です。", error),
            EVRInitError.IPC_ConnectFailedAfterMultipleAttempts => new EVRIPCInitializeException("複数回の試行後、IPC接続に失敗しました。", error),
            EVRInitError.IPC_ConnectFailedAfterTargetExited => new EVRIPCInitializeException("ターゲット終了後、IPC接続に失敗しました。", error),
            EVRInitError.IPC_NamespaceUnavailable => new EVRIPCInitializeException("IPCネームスペースを利用できません。", error),

            // --- コンポジター関連 ---
            EVRInitError.Compositor_Failed => new EVRCompositorInitializeException("コンポジターが失敗しました。", error),
            EVRInitError.Compositor_D3D11HardwareRequired => new EVRCompositorInitializeException("Direct3D11ハードウェアが必要です。", error),
            EVRInitError.Compositor_FirmwareRequiresUpdate => new EVRCompositorInitializeException("コンポジター用にファームウェアの更新が必要です。", error),
            EVRInitError.Compositor_OverlayInitFailed => new EVRCompositorInitializeException("コンポジターオーバーレイの初期化に失敗しました。", error),
            EVRInitError.Compositor_ScreenshotsInitFailed => new EVRCompositorInitializeException("コンポジタースクリーンショットの初期化に失敗しました。", error),
            EVRInitError.Compositor_UnableToCreateDevice => new EVRCompositorInitializeException("グラフィックスデバイスを作成できませんでした。", error),
            EVRInitError.Compositor_SharedStateIsNull => new EVRCompositorInitializeException("共有ステートがnullです。", error),
            EVRInitError.Compositor_NotificationManagerIsNull => new EVRCompositorInitializeException("通知マネージャーがnullです。", error),
            EVRInitError.Compositor_ResourceManagerClientIsNull => new EVRCompositorInitializeException("リソースマネージャークライアントがnullです。", error),
            EVRInitError.Compositor_MessageOverlaySharedStateInitFailure => new EVRCompositorInitializeException("メッセージオーバーレイ共有ステートの初期化に失敗しました。", error),
            EVRInitError.Compositor_PropertiesInterfaceIsNull => new EVRCompositorInitializeException("プロパティインターフェースがnullです。", error),
            EVRInitError.Compositor_CreateFullscreenWindowFailed => new EVRCompositorInitializeException("全画面ウィンドウの作成に失敗しました。", error),
            EVRInitError.Compositor_SettingsInterfaceIsNull => new EVRCompositorInitializeException("設定インターフェースがnullです。", error),
            EVRInitError.Compositor_FailedToShowWindow => new EVRCompositorInitializeException("ウィンドウの表示に失敗しました。", error),
            EVRInitError.Compositor_DistortInterfaceIsNull => new EVRCompositorInitializeException("歪み補正インターフェースがnullです。", error),
            EVRInitError.Compositor_DisplayFrequencyFailure => new EVRCompositorInitializeException("ディスプレイ周波数の取得に失敗しました。", error),
            EVRInitError.Compositor_RendererInitializationFailed => new EVRCompositorInitializeException("レンダラーの初期化に失敗しました。", error),
            EVRInitError.Compositor_DXGIFactoryInterfaceIsNull => new EVRCompositorInitializeException("DXGIファクトリインターフェースがnullです。", error),
            EVRInitError.Compositor_DXGIFactoryCreateFailed => new EVRCompositorInitializeException("DXGIファクトリの作成に失敗しました。", error),
            EVRInitError.Compositor_DXGIFactoryQueryFailed => new EVRCompositorInitializeException("DXGIファクトリのクエリに失敗しました。", error),
            EVRInitError.Compositor_InvalidAdapterDesktop => new EVRCompositorInitializeException("デスクトップアダプターが無効です。", error),
            EVRInitError.Compositor_InvalidHmdAttachment => new EVRCompositorInitializeException("HMDの接続が無効です。", error),
            EVRInitError.Compositor_InvalidOutputDesktop => new EVRCompositorInitializeException("出力デスクトップが無効です。", error),
            EVRInitError.Compositor_InvalidDeviceProvided => new EVRCompositorInitializeException("提供されたデバイスが無効です。", error),
            EVRInitError.Compositor_D3D11RendererInitializationFailed => new EVRCompositorInitializeException("D3D11レンダラーの初期化に失敗しました。", error),
            EVRInitError.Compositor_FailedToFindDisplayMode => new EVRCompositorInitializeException("ディスプレイモードが見つかりませんでした。", error),
            EVRInitError.Compositor_FailedToCreateSwapChain => new EVRCompositorInitializeException("スワップチェーンの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToGetBackBuffer => new EVRCompositorInitializeException("バックバッファの取得に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateRenderTarget => new EVRCompositorInitializeException("レンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDXGI2SwapChain => new EVRCompositorInitializeException("DXGI2スワップチェーンの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedtoGetDXGI2BackBuffer => new EVRCompositorInitializeException("DXGI2バックバッファの取得に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDXGI2RenderTarget => new EVRCompositorInitializeException("DXGI2レンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToGetDXGIDeviceInterface => new EVRCompositorInitializeException("DXGIデバイスインターフェースの取得に失敗しました。", error),
            EVRInitError.Compositor_SelectDisplayMode => new EVRCompositorInitializeException("ディスプレイモードの選択に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateNvAPIRenderTargets => new EVRCompositorInitializeException("NvAPIレンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_NvAPISetDisplayMode => new EVRCompositorInitializeException("NvAPIディスプレイモード設定に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDirectModeDisplay => new EVRCompositorInitializeException("ダイレクトモードディスプレイの作成に失敗しました。", error),
            EVRInitError.Compositor_InvalidHmdPropertyContainer => new EVRCompositorInitializeException("HMDプロパティコンテナが無効です。", error),
            EVRInitError.Compositor_UpdateDisplayFrequency => new EVRCompositorInitializeException("ディスプレイ周波数の更新に失敗しました。", error),
            EVRInitError.Compositor_CreateRasterizerState => new EVRCompositorInitializeException("ラスタライザステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateWireframeRasterizerState => new EVRCompositorInitializeException("ワイヤーフレームラスタライザステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSamplerState => new EVRCompositorInitializeException("サンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateClampToBorderSamplerState => new EVRCompositorInitializeException("ClampToBorderサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateAnisoSamplerState => new EVRCompositorInitializeException("異方性サンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlaySamplerState => new EVRCompositorInitializeException("オーバーレイサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePanoramaSamplerState => new EVRCompositorInitializeException("パノラマサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateFontSamplerState => new EVRCompositorInitializeException("フォントサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateNoBlendState => new EVRCompositorInitializeException("NoBlendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendState => new EVRCompositorInitializeException("Blendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateAlphaBlendState => new EVRCompositorInitializeException("AlphaBlendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskR => new EVRCompositorInitializeException("BlendStateMaskRの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskG => new EVRCompositorInitializeException("BlendStateMaskGの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskB => new EVRCompositorInitializeException("BlendStateMaskBの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilState => new EVRCompositorInitializeException("深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilStateNoWrite => new EVRCompositorInitializeException("NoWrite深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilStateNoDepth => new EVRCompositorInitializeException("NoDepth深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateFlushTexture => new EVRCompositorInitializeException("Flushテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDistortionSurfaces => new EVRCompositorInitializeException("歪み補正サーフェスの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateConstantBuffer => new EVRCompositorInitializeException("定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateHmdPoseConstantBuffer => new EVRCompositorInitializeException("HMDポーズ定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateHmdPoseStagingConstantBuffer => new EVRCompositorInitializeException("HMDポーズステージングバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSharedFrameInfoConstantBuffer => new EVRCompositorInitializeException("フレーム情報共有バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayConstantBuffer => new EVRCompositorInitializeException("オーバーレイ定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSceneTextureIndexConstantBuffer => new EVRCompositorInitializeException("シーンテクスチャインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateReadableSceneTextureIndexConstantBuffer => new EVRCompositorInitializeException("読み取り可能シーンテクスチャインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerGraphicsTextureIndexConstantBuffer => new EVRCompositorInitializeException("レイヤーグラフィックスインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerComputeTextureIndexConstantBuffer => new EVRCompositorInitializeException("レイヤー演算インデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerComputeSceneTextureIndexConstantBuffer => new EVRCompositorInitializeException("レイヤー演算シーンインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateComputeHmdPoseConstantBuffer => new EVRCompositorInitializeException("演算用HMDポーズバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateGeomConstantBuffer => new EVRCompositorInitializeException("幾何定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePanelMaskConstantBuffer => new EVRCompositorInitializeException("パネルマスクバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePixelSimUBO => new EVRCompositorInitializeException("PixelSimUBOの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMSAARenderTextures => new EVRCompositorInitializeException("MSAAレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateResolveRenderTextures => new EVRCompositorInitializeException("Resolveレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateComputeResolveRenderTextures => new EVRCompositorInitializeException("演算用Resolveレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDriverDirectModeResolveTextures => new EVRCompositorInitializeException("ドライバダイレクトResolveテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_OpenDriverDirectModeResolveTextures => new EVRCompositorInitializeException("ドライバダイレクトResolveテクスチャを開けませんでした。", error),
            EVRInitError.Compositor_CreateFallbackSyncTexture => new EVRCompositorInitializeException("フォールバック同期テクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_ShareFallbackSyncTexture => new EVRCompositorInitializeException("フォールバック同期テクスチャの共有に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayIndexBuffer => new EVRCompositorInitializeException("オーバーレイインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayVertexBuffer => new EVRCompositorInitializeException("オーバーレイ頂点バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateTextVertexBuffer => new EVRCompositorInitializeException("テキスト頂点バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateTextIndexBuffer => new EVRCompositorInitializeException("テキストインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMirrorTextures => new EVRCompositorInitializeException("ミラーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLastFrameRenderTexture => new EVRCompositorInitializeException("直前フレームレンダリングテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMirrorOverlay => new EVRCompositorInitializeException("ミラーオーバーレイの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateVirtualDisplayBackbuffer => new EVRCompositorInitializeException("仮想ディスプレイバックバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_DisplayModeNotSupported => new EVRCompositorInitializeException("ディスプレイモードがサポートされていません。", error),
            EVRInitError.Compositor_CreateOverlayInvalidCall => new EVRCompositorInitializeException("オーバーレイ作成呼び出しが無効です。", error),
            EVRInitError.Compositor_CreateOverlayAlreadyInitialized => new EVRCompositorInitializeException("オーバーレイは既に初期化されています。", error),
            EVRInitError.Compositor_FailedToCreateMailbox => new EVRCompositorInitializeException("メールボックスの作成に失敗しました。", error),
            EVRInitError.Compositor_WindowInterfaceIsNull => new EVRCompositorInitializeException("ウィンドウインターフェースがnullです。", error),
            EVRInitError.Compositor_SystemLayerCreateInstance => new EVRCompositorInitializeException("システムレイヤーインスタンスの作成に失敗しました。", error),
            EVRInitError.Compositor_SystemLayerCreateSession => new EVRCompositorInitializeException("システムレイヤーセッションの作成に失敗しました。", error),

            // --- ベンダー固有エラー (Oculus/Meta等) ---
            EVRInitError.VendorSpecific_UnableToConnectToOculusRuntime => new EVRVendorSpecificInitializeException("Oculusランタイムに接続できません。", error),
            EVRInitError.VendorSpecific_WindowsNotInDevMode => new EVRVendorSpecificInitializeException("Windowsが開発者モードではありません。", error),
            EVRInitError.VendorSpecific_HmdFound_CantOpenDevice => new EVRVendorSpecificInitializeException("HMDデバイスを開けませんでした。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToRequestConfigStart => new EVRVendorSpecificInitializeException("HMD構成開始の要求に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_NoStoredConfig => new EVRVendorSpecificInitializeException("HMD内に保存された構成がありません。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigTooBig => new EVRVendorSpecificInitializeException("HMD構成データが大きすぎます。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigTooSmall => new EVRVendorSpecificInitializeException("HMD構成データが小さすぎます。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToInitZLib => new EVRVendorSpecificInitializeException("zlibの初期化に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_CantReadFirmwareVersion => new EVRVendorSpecificInitializeException("ファームウェアバージョンの読み取りに失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToSendUserDataStart => new EVRVendorSpecificInitializeException("ユーザーデータ送信開始に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToGetUserDataStart => new EVRVendorSpecificInitializeException("ユーザーデータ取得開始に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToGetUserDataNext => new EVRVendorSpecificInitializeException("ユーザーデータ次フレーム取得に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UserDataAddressRange => new EVRVendorSpecificInitializeException("ユーザーデータのアドレス範囲エラーです。", error),
            EVRInitError.VendorSpecific_HmdFound_UserDataError => new EVRVendorSpecificInitializeException("ユーザーデータエラーが発生しました。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigFailedSanityCheck => new EVRVendorSpecificInitializeException("HMD構成データの整合性チェックに失敗しました。", error),
            EVRInitError.VendorSpecific_OculusRuntimeBadInstall => new EVRVendorSpecificInitializeException("Oculusランタイムのインストールが不完全です。", error),

            // --- その他 ---
            EVRInitError.Steam_SteamInstallationNotFound => new EVRInitializeException("Steamのインストールが見つかりません。", error),
            EVRInitError.LastError => new EVRInitializeException("最後のエラーが発生しました。", error),

            _ => throw new ArgumentOutOfRangeException(nameof(error), error, $"予期しない初期化エラーが発生しました: {error}")
        };
    }
}