using Valve.VR;

namespace FloatSoda.Exceptions;

public class VrInitialException(string message, EVRInitError errorCode) : OpenVrException<EVRInitError>(message, errorCode);

public static class VrInitialExceptionValidator
{
    public static void ThrowIfError(this EVRInitError error)
    {
        if (error == EVRInitError.None) return;

        throw error switch {
            // --- 一般的な初期化エラー ---
            EVRInitError.Unknown => new VrInitialException("未知の初期化エラーが発生しました。", error),
            EVRInitError.Init_InstallationNotFound => new VrInitialException("OpenVRのインストールが見つかりません。", error),
            EVRInitError.Init_InstallationCorrupt => new VrInitialException("OpenVRのインストールが壊れています。", error),
            EVRInitError.Init_VRClientDLLNotFound => new VrInitialException("vrclient.dllが見つかりません。", error),
            EVRInitError.Init_FileNotFound => new VrInitialException("必要な構成ファイルが見つかりません。", error),
            EVRInitError.Init_FactoryNotFound => new VrInitialException("ファクトリインターフェースの取得に失敗しました。", error),
            EVRInitError.Init_InterfaceNotFound => new VrInitialException("要求されたインターフェースが見つかりません。", error),
            EVRInitError.Init_InvalidInterface => new VrInitialException("インターフェースが無効です。", error),
            EVRInitError.Init_UserConfigDirectoryInvalid => new VrInitialException("ユーザー設定ディレクトリが無効です。", error),
            EVRInitError.Init_HmdNotFound => new VrInitialException("HMDが見つからないか、接続されていません。", error),
            EVRInitError.Init_NotInitialized => new VrInitialException("OpenVRが初期化されていません。", error),
            EVRInitError.Init_PathRegistryNotFound => new VrInitialException("パスレジストリが見つかりません。", error),
            EVRInitError.Init_NoConfigPath => new VrInitialException("構成パスが設定されていません。", error),
            EVRInitError.Init_NoLogPath => new VrInitialException("ログパスが設定されていません。", error),
            EVRInitError.Init_PathRegistryNotWritable => new VrInitialException("パスレジストリに書き込めません。", error),
            EVRInitError.Init_AppInfoInitFailed => new VrInitialException("アプリケーション情報の初期化に失敗しました。", error),
            EVRInitError.Init_Retry => new VrInitialException("再試行が必要です。", error),
            EVRInitError.Init_InitCanceledByUser => new VrInitialException("ユーザーによって初期化がキャンセルされました。", error),
            EVRInitError.Init_AnotherAppLaunching => new VrInitialException("別のアプリケーションが起動中です。", error),
            EVRInitError.Init_SettingsInitFailed => new VrInitialException("設定の初期化に失敗しました。", error),
            EVRInitError.Init_ShuttingDown => new VrInitialException("システムが終了処理中です。", error),
            EVRInitError.Init_TooManyObjects => new VrInitialException("オブジェクトが多すぎます。", error),
            EVRInitError.Init_NoServerForBackgroundApp => new VrInitialException("バックグラウンドアプリ用のサーバーがありません。", error),
            EVRInitError.Init_NotSupportedWithCompositor => new VrInitialException("コンポジター使用時はサポートされません。", error),
            EVRInitError.Init_NotAvailableToUtilityApps => new VrInitialException("ユーティリティアプリでは利用できません。", error),
            EVRInitError.Init_Internal => new VrInitialException("内部エラーが発生しました。", error),
            EVRInitError.Init_HmdDriverIdIsNone => new VrInitialException("HMDドライバIDがNoneです。", error),
            EVRInitError.Init_HmdNotFoundPresenceFailed => new VrInitialException("HMDの存在確認に失敗しました。", error),
            EVRInitError.Init_VRMonitorNotFound => new VrInitialException("VRモニターが見つかりません。", error),
            EVRInitError.Init_VRMonitorStartupFailed => new VrInitialException("VRモニターの起動に失敗しました。", error),
            EVRInitError.Init_LowPowerWatchdogNotSupported => new VrInitialException("低電力ウォッチドッグはサポートされていません。", error),
            EVRInitError.Init_InvalidApplicationType => new VrInitialException("アプリケーションタイプが無効です。", error),
            EVRInitError.Init_NotAvailableToWatchdogApps => new VrInitialException("ウォッチドッグアプリでは利用できません。", error),
            EVRInitError.Init_WatchdogDisabledInSettings => new VrInitialException("設定でウォッチドッグが無効になっています。", error),
            EVRInitError.Init_VRDashboardNotFound => new VrInitialException("VRダッシュボードが見つかりません。", error),
            EVRInitError.Init_VRDashboardStartupFailed => new VrInitialException("VRダッシュボードの起動に失敗しました。", error),
            EVRInitError.Init_VRHomeNotFound => new VrInitialException("VR Homeが見つかりません。", error),
            EVRInitError.Init_VRHomeStartupFailed => new VrInitialException("VR Homeの起動に失敗しました。", error),
            EVRInitError.Init_RebootingBusy => new VrInitialException("再起動処理中のためビジーです。", error),
            EVRInitError.Init_FirmwareUpdateBusy => new VrInitialException("ファームウェア更新中のためビジーです。", error),
            EVRInitError.Init_FirmwareRecoveryBusy => new VrInitialException("ファームウェア復旧中のためビジーです。", error),
            EVRInitError.Init_USBServiceBusy => new VrInitialException("USBサービスがビジーです。", error),
            EVRInitError.Init_VRWebHelperStartupFailed => new VrInitialException("VR Web Helperの起動に失敗しました。", error),
            EVRInitError.Init_TrackerManagerInitFailed => new VrInitialException("トラッカーマネージャーの初期化に失敗しました。", error),
            EVRInitError.Init_AlreadyRunning => new VrInitialException("既に実行中です。", error),
            EVRInitError.Init_FailedForVrMonitor => new VrInitialException("VRモニター用プロセスの初期化に失敗しました。", error),
            EVRInitError.Init_PropertyManagerInitFailed => new VrInitialException("プロパティマネージャーの初期化に失敗しました。", error),
            EVRInitError.Init_WebServerFailed => new VrInitialException("Webサーバーの起動に失敗しました。", error),
            EVRInitError.Init_IllegalTypeTransition => new VrInitialException("不正なタイプ遷移です。", error),
            EVRInitError.Init_MismatchedRuntimes => new VrInitialException("ランタイムのバージョンが一致しません。", error),
            EVRInitError.Init_InvalidProcessId => new VrInitialException("プロセスIDが無効です。", error),
            EVRInitError.Init_VRServiceStartupFailed => new VrInitialException("VRサービスの起動に失敗しました。", error),
            EVRInitError.Init_PrismNeedsNewDrivers => new VrInitialException("Prismドライバの更新が必要です。", error),
            EVRInitError.Init_PrismStartupTimedOut => new VrInitialException("Prismの起動がタイムアウトしました。", error),
            EVRInitError.Init_CouldNotStartPrism => new VrInitialException("Prismを起動できませんでした。", error),
            EVRInitError.Init_CreateDriverDirectDeviceFailed => new VrInitialException("ドライバダイレクトデバイスの作成に失敗しました。", error),
            EVRInitError.Init_PrismExitedUnexpectedly => new VrInitialException("Prismが予期せず終了しました。", error),

            // --- ドライバ関連 ---
            EVRInitError.Driver_Failed => new VrInitialException("ドライバのエラーです。", error),
            EVRInitError.Driver_Unknown => new VrInitialException("未知のドライバエラーです。", error),
            EVRInitError.Driver_HmdUnknown => new VrInitialException("未知のHMDドライバです。", error),
            EVRInitError.Driver_NotLoaded => new VrInitialException("ドライバがロードされていません。", error),
            EVRInitError.Driver_RuntimeOutOfDate => new VrInitialException("ドライバのランタイムが古すぎます。", error),
            EVRInitError.Driver_HmdInUse => new VrInitialException("HMDが別のプロセスで使用中です。", error),
            EVRInitError.Driver_NotCalibrated => new VrInitialException("ドライバが校正されていません。", error),
            EVRInitError.Driver_CalibrationInvalid => new VrInitialException("ドライバの校正データが無効です。", error),
            EVRInitError.Driver_HmdDisplayNotFound => new VrInitialException("HMDのディスプレイが見つかりません。", error),
            EVRInitError.Driver_TrackedDeviceInterfaceUnknown => new VrInitialException("トラッキングデバイスインターフェースが不明です。", error),
            EVRInitError.Driver_HmdDriverIdOutOfBounds => new VrInitialException("HMDドライバIDが範囲外です。", error),
            EVRInitError.Driver_HmdDisplayMirrored => new VrInitialException("HMDディスプレイがミラーリング設定になっています。", error),
            EVRInitError.Driver_HmdDisplayNotFoundLaptop => new VrInitialException("ラップトップ用HMDディスプレイが見つかりません。", error),

            // --- IPC (プロセス間通信) 関連 ---
            EVRInitError.IPC_ServerInitFailed => new VrInitialException("IPCサーバーの初期化に失敗しました。", error),
            EVRInitError.IPC_ConnectFailed => new VrInitialException("IPC接続に失敗しました。", error),
            EVRInitError.IPC_SharedStateInitFailed => new VrInitialException("共有ステートの初期化に失敗しました。", error),
            EVRInitError.IPC_CompositorInitFailed => new VrInitialException("コンポジターの初期化に失敗しました。", error),
            EVRInitError.IPC_MutexInitFailed => new VrInitialException("Mutexの初期化に失敗しました。", error),
            EVRInitError.IPC_Failed => new VrInitialException("IPC接続エラーが発生しました。", error),
            EVRInitError.IPC_CompositorConnectFailed => new VrInitialException("コンポジターへの接続に失敗しました。", error),
            EVRInitError.IPC_CompositorInvalidConnectResponse => new VrInitialException("コンポジターからの接続レスポンスが無効です。", error),
            EVRInitError.IPC_ConnectFailedAfterMultipleAttempts => new VrInitialException("複数回の試行後、IPC接続に失敗しました。", error),
            EVRInitError.IPC_ConnectFailedAfterTargetExited => new VrInitialException("ターゲット終了後、IPC接続に失敗しました。", error),
            EVRInitError.IPC_NamespaceUnavailable => new VrInitialException("IPCネームスペースを利用できません。", error),

            // --- コンポジター関連 ---
            EVRInitError.Compositor_Failed => new VrInitialException("コンポジターが失敗しました。", error),
            EVRInitError.Compositor_D3D11HardwareRequired => new VrInitialException("Direct3D11ハードウェアが必要です。", error),
            EVRInitError.Compositor_FirmwareRequiresUpdate => new VrInitialException("コンポジター用にファームウェアの更新が必要です。", error),
            EVRInitError.Compositor_OverlayInitFailed => new VrInitialException("コンポジターオーバーレイの初期化に失敗しました。", error),
            EVRInitError.Compositor_ScreenshotsInitFailed => new VrInitialException("コンポジタースクリーンショットの初期化に失敗しました。", error),
            EVRInitError.Compositor_UnableToCreateDevice => new VrInitialException("グラフィックスデバイスを作成できませんでした。", error),
            EVRInitError.Compositor_SharedStateIsNull => new VrInitialException("共有ステートがnullです。", error),
            EVRInitError.Compositor_NotificationManagerIsNull => new VrInitialException("通知マネージャーがnullです。", error),
            EVRInitError.Compositor_ResourceManagerClientIsNull => new VrInitialException("リソースマネージャークライアントがnullです。", error),
            EVRInitError.Compositor_MessageOverlaySharedStateInitFailure => new VrInitialException("メッセージオーバーレイ共有ステートの初期化に失敗しました。", error),
            EVRInitError.Compositor_PropertiesInterfaceIsNull => new VrInitialException("プロパティインターフェースがnullです。", error),
            EVRInitError.Compositor_CreateFullscreenWindowFailed => new VrInitialException("全画面ウィンドウの作成に失敗しました。", error),
            EVRInitError.Compositor_SettingsInterfaceIsNull => new VrInitialException("設定インターフェースがnullです。", error),
            EVRInitError.Compositor_FailedToShowWindow => new VrInitialException("ウィンドウの表示に失敗しました。", error),
            EVRInitError.Compositor_DistortInterfaceIsNull => new VrInitialException("歪み補正インターフェースがnullです。", error),
            EVRInitError.Compositor_DisplayFrequencyFailure => new VrInitialException("ディスプレイ周波数の取得に失敗しました。", error),
            EVRInitError.Compositor_RendererInitializationFailed => new VrInitialException("レンダラーの初期化に失敗しました。", error),
            EVRInitError.Compositor_DXGIFactoryInterfaceIsNull => new VrInitialException("DXGIファクトリインターフェースがnullです。", error),
            EVRInitError.Compositor_DXGIFactoryCreateFailed => new VrInitialException("DXGIファクトリの作成に失敗しました。", error),
            EVRInitError.Compositor_DXGIFactoryQueryFailed => new VrInitialException("DXGIファクトリのクエリに失敗しました。", error),
            EVRInitError.Compositor_InvalidAdapterDesktop => new VrInitialException("デスクトップアダプターが無効です。", error),
            EVRInitError.Compositor_InvalidHmdAttachment => new VrInitialException("HMDの接続が無効です。", error),
            EVRInitError.Compositor_InvalidOutputDesktop => new VrInitialException("出力デスクトップが無効です。", error),
            EVRInitError.Compositor_InvalidDeviceProvided => new VrInitialException("提供されたデバイスが無効です。", error),
            EVRInitError.Compositor_D3D11RendererInitializationFailed => new VrInitialException("D3D11レンダラーの初期化に失敗しました。", error),
            EVRInitError.Compositor_FailedToFindDisplayMode => new VrInitialException("ディスプレイモードが見つかりませんでした。", error),
            EVRInitError.Compositor_FailedToCreateSwapChain => new VrInitialException("スワップチェーンの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToGetBackBuffer => new VrInitialException("バックバッファの取得に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateRenderTarget => new VrInitialException("レンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDXGI2SwapChain => new VrInitialException("DXGI2スワップチェーンの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedtoGetDXGI2BackBuffer => new VrInitialException("DXGI2バックバッファの取得に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDXGI2RenderTarget => new VrInitialException("DXGI2レンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToGetDXGIDeviceInterface => new VrInitialException("DXGIデバイスインターフェースの取得に失敗しました。", error),
            EVRInitError.Compositor_SelectDisplayMode => new VrInitialException("ディスプレイモードの選択に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateNvAPIRenderTargets => new VrInitialException("NvAPIレンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_NvAPISetDisplayMode => new VrInitialException("NvAPIディスプレイモード設定に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDirectModeDisplay => new VrInitialException("ダイレクトモードディスプレイの作成に失敗しました。", error),
            EVRInitError.Compositor_InvalidHmdPropertyContainer => new VrInitialException("HMDプロパティコンテナが無効です。", error),
            EVRInitError.Compositor_UpdateDisplayFrequency => new VrInitialException("ディスプレイ周波数の更新に失敗しました。", error),
            EVRInitError.Compositor_CreateRasterizerState => new VrInitialException("ラスタライザステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateWireframeRasterizerState => new VrInitialException("ワイヤーフレームラスタライザステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSamplerState => new VrInitialException("サンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateClampToBorderSamplerState => new VrInitialException("ClampToBorderサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateAnisoSamplerState => new VrInitialException("異方性サンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlaySamplerState => new VrInitialException("オーバーレイサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePanoramaSamplerState => new VrInitialException("パノラマサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateFontSamplerState => new VrInitialException("フォントサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateNoBlendState => new VrInitialException("NoBlendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendState => new VrInitialException("Blendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateAlphaBlendState => new VrInitialException("AlphaBlendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskR => new VrInitialException("BlendStateMaskRの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskG => new VrInitialException("BlendStateMaskGの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskB => new VrInitialException("BlendStateMaskBの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilState => new VrInitialException("深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilStateNoWrite => new VrInitialException("NoWrite深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilStateNoDepth => new VrInitialException("NoDepth深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateFlushTexture => new VrInitialException("Flushテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDistortionSurfaces => new VrInitialException("歪み補正サーフェスの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateConstantBuffer => new VrInitialException("定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateHmdPoseConstantBuffer => new VrInitialException("HMDポーズ定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateHmdPoseStagingConstantBuffer => new VrInitialException("HMDポーズステージングバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSharedFrameInfoConstantBuffer => new VrInitialException("フレーム情報共有バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayConstantBuffer => new VrInitialException("オーバーレイ定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSceneTextureIndexConstantBuffer => new VrInitialException("シーンテクスチャインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateReadableSceneTextureIndexConstantBuffer => new VrInitialException("読み取り可能シーンテクスチャインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerGraphicsTextureIndexConstantBuffer => new VrInitialException("レイヤーグラフィックスインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerComputeTextureIndexConstantBuffer => new VrInitialException("レイヤー演算インデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerComputeSceneTextureIndexConstantBuffer => new VrInitialException("レイヤー演算シーンインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateComputeHmdPoseConstantBuffer => new VrInitialException("演算用HMDポーズバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateGeomConstantBuffer => new VrInitialException("幾何定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePanelMaskConstantBuffer => new VrInitialException("パネルマスクバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePixelSimUBO => new VrInitialException("PixelSimUBOの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMSAARenderTextures => new VrInitialException("MSAAレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateResolveRenderTextures => new VrInitialException("Resolveレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateComputeResolveRenderTextures => new VrInitialException("演算用Resolveレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDriverDirectModeResolveTextures => new VrInitialException("ドライバダイレクトResolveテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_OpenDriverDirectModeResolveTextures => new VrInitialException("ドライバダイレクトResolveテクスチャを開けませんでした。", error),
            EVRInitError.Compositor_CreateFallbackSyncTexture => new VrInitialException("フォールバック同期テクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_ShareFallbackSyncTexture => new VrInitialException("フォールバック同期テクスチャの共有に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayIndexBuffer => new VrInitialException("オーバーレイインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayVertexBuffer => new VrInitialException("オーバーレイ頂点バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateTextVertexBuffer => new VrInitialException("テキスト頂点バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateTextIndexBuffer => new VrInitialException("テキストインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMirrorTextures => new VrInitialException("ミラーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLastFrameRenderTexture => new VrInitialException("直前フレームレンダリングテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMirrorOverlay => new VrInitialException("ミラーオーバーレイの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateVirtualDisplayBackbuffer => new VrInitialException("仮想ディスプレイバックバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_DisplayModeNotSupported => new VrInitialException("ディスプレイモードがサポートされていません。", error),
            EVRInitError.Compositor_CreateOverlayInvalidCall => new VrInitialException("オーバーレイ作成呼び出しが無効です。", error),
            EVRInitError.Compositor_CreateOverlayAlreadyInitialized => new VrInitialException("オーバーレイは既に初期化されています。", error),
            EVRInitError.Compositor_FailedToCreateMailbox => new VrInitialException("メールボックスの作成に失敗しました。", error),
            EVRInitError.Compositor_WindowInterfaceIsNull => new VrInitialException("ウィンドウインターフェースがnullです。", error),
            EVRInitError.Compositor_SystemLayerCreateInstance => new VrInitialException("システムレイヤーインスタンスの作成に失敗しました。", error),
            EVRInitError.Compositor_SystemLayerCreateSession => new VrInitialException("システムレイヤーセッションの作成に失敗しました。", error),

            // --- ベンダー固有エラー (Oculus/Meta等) ---
            EVRInitError.VendorSpecific_UnableToConnectToOculusRuntime => new VrInitialException("Oculusランタイムに接続できません。", error),
            EVRInitError.VendorSpecific_WindowsNotInDevMode => new VrInitialException("Windowsが開発者モードではありません。", error),
            EVRInitError.VendorSpecific_HmdFound_CantOpenDevice => new VrInitialException("HMDデバイスを開けませんでした。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToRequestConfigStart => new VrInitialException("HMD構成開始の要求に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_NoStoredConfig => new VrInitialException("HMD内に保存された構成がありません。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigTooBig => new VrInitialException("HMD構成データが大きすぎます。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigTooSmall => new VrInitialException("HMD構成データが小さすぎます。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToInitZLib => new VrInitialException("zlibの初期化に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_CantReadFirmwareVersion => new VrInitialException("ファームウェアバージョンの読み取りに失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToSendUserDataStart => new VrInitialException("ユーザーデータ送信開始に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToGetUserDataStart => new VrInitialException("ユーザーデータ取得開始に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToGetUserDataNext => new VrInitialException("ユーザーデータ次フレーム取得に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UserDataAddressRange => new VrInitialException("ユーザーデータのアドレス範囲エラーです。", error),
            EVRInitError.VendorSpecific_HmdFound_UserDataError => new VrInitialException("ユーザーデータエラーが発生しました。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigFailedSanityCheck => new VrInitialException("HMD構成データの整合性チェックに失敗しました。", error),
            EVRInitError.VendorSpecific_OculusRuntimeBadInstall => new VrInitialException("Oculusランタイムのインストールが不完全です。", error),

            // --- その他 ---
            EVRInitError.Steam_SteamInstallationNotFound => new VrInitialException("Steamのインストールが見つかりません。", error),
            EVRInitError.LastError => new VrInitialException("最後のエラーが発生しました。", error),

            _ => throw new ArgumentOutOfRangeException(nameof(error), error, $"予期しない初期化エラーが発生しました: {error}")
        };
    }
}