using System.Text.Json;
using System.Text.Json.Nodes;

namespace FloatSoda.OVR.Input;

/// <summary>
/// C#で宣言された <see cref="InputActionMap"/> 群から、OpenVRのアクションマニフェストJSONと
/// コントローラー別デフォルトバインディングJSONを生成します。
/// FloatSodaでは入力定義もすべてC#コードで完結させ、ユーザーがJSONを書くことはありません。
/// </summary>
public static class ActionManifestWriter
{
    private static readonly JsonSerializerOptions WriteOptions = new() { WriteIndented = true };

    private static readonly ControllerType[] AllControllers =
        [ControllerType.Index, ControllerType.ViveWand, ControllerType.OculusTouch];

    /// <summary>
    /// マニフェスト一式をディレクトリへ書き出し、アクションマニフェストのフルパスを返します。
    /// </summary>
    /// <param name="appKey">出力先ディレクトリの分離に使うアプリケーションキー。</param>
    /// <param name="maps">書き出すアクションマップの一覧。</param>
    /// <param name="outputDirectory">出力先。省略時は一時ディレクトリ配下(<c>%TEMP%/FloatSoda/{AppKey}/input</c>)。</param>
    /// <returns><c>IVRInput.SetActionManifestPath</c> へ渡すアクションマニフェストの絶対パス。</returns>
    public static string Write(AppKey appKey, IReadOnlyList<InputActionMap> maps, string? outputDirectory = null)
    {
        var directory = outputDirectory
                        ?? Path.Combine(Path.GetTempPath(), "FloatSoda", appKey.Value, "input");
        Directory.CreateDirectory(directory);

        foreach (var controller in AllControllers)
        {
            var fileName = BindingFileName(controller);
            File.WriteAllText(
                Path.Combine(directory, fileName),
                BuildBindings(controller, maps).ToJsonString(WriteOptions));
        }

        var manifestPath = Path.Combine(directory, "actions.json");
        File.WriteAllText(manifestPath, BuildManifest(maps).ToJsonString(WriteOptions));
        return manifestPath;
    }

    private static string BindingFileName(ControllerType controller)
        => $"bindings_{InputPaths.ControllerName(controller)}.json";

    internal static JsonObject BuildManifest(IReadOnlyList<InputActionMap> maps)
    {
        var actions = new JsonArray();
        var actionSets = new JsonArray();
        var localization = new JsonObject { ["language_tag"] = "en_US" };

        foreach (var map in maps)
        {
            var setPath = InputPaths.ActionSetPath(map.Name);
            actionSets.Add(new JsonObject { ["name"] = setPath, ["usage"] = "leftright" });
            localization[setPath] = map.Name;

            foreach (var action in map.Actions)
            {
                var actionPath = InputPaths.ActionPath(map.Name, action.Name);
                actions.Add(new JsonObject
                {
                    ["name"] = actionPath,
                    ["type"] = action.ManifestType,
                    ["requirement"] = "optional",
                });
                localization[actionPath] = action.LocalizedName ?? action.Name;
            }
        }

        var defaultBindings = new JsonArray();
        foreach (var controller in AllControllers)
        {
            defaultBindings.Add(new JsonObject
            {
                ["controller_type"] = InputPaths.ControllerName(controller),
                ["binding_url"] = BindingFileName(controller),
            });
        }

        return new JsonObject
        {
            ["default_bindings"] = defaultBindings,
            ["actions"] = actions,
            ["action_sets"] = actionSets,
            ["localization"] = new JsonArray(localization),
        };
    }

    internal static JsonObject BuildBindings(ControllerType controller, IReadOnlyList<InputActionMap> maps)
    {
        var bindings = new JsonObject();

        foreach (var map in maps)
        {
            var sources = new JsonArray();
            foreach (var action in map.Actions)
            {
                var output = InputPaths.ActionPath(map.Name, action.Name);
                foreach (var inputPath in action.BindingPathsFor(controller))
                {
                    var (source, component, mode) = SplitInputPath(inputPath, action.ManifestType);
                    sources.Add(new JsonObject
                    {
                        ["path"] = source,
                        ["mode"] = mode,
                        ["inputs"] = new JsonObject
                        {
                            [component] = new JsonObject { ["output"] = output },
                        },
                    });
                }
            }

            bindings[InputPaths.ActionSetPath(map.Name)] = new JsonObject { ["sources"] = sources };
        }

        return new JsonObject
        {
            ["controller_type"] = InputPaths.ControllerName(controller),
            ["name"] = "FloatSoda default bindings",
            ["description"] = "Generated by FloatSoda ActionManifestWriter.",
            ["bindings"] = bindings,
        };
    }

    /// <summary>
    /// 入力パスをバインディングJSONが要求する (ソースパス, 入力コンポーネント, モード) に分解します。
    /// 末尾が既知のコンポーネント(click/touch/pull/position)ならそれを、無ければアクション型から補完します。
    /// </summary>
    private static (string Source, string Component, string Mode) SplitInputPath(string inputPath, string manifestType)
    {
        var lastSlash = inputPath.LastIndexOf('/');
        var lastSegment = lastSlash >= 0 ? inputPath[(lastSlash + 1)..] : inputPath;

        string source, component;
        if (lastSegment is "click" or "touch" or "pull" or "position")
        {
            source = inputPath[..lastSlash];
            component = lastSegment;
        }
        else
        {
            source = inputPath;
            component = manifestType switch
            {
                "boolean" => "click",
                "vector1" => "pull",
                _ => "position",
            };
        }

        var mode = component switch
        {
            "pull" => "trigger",
            "position" => source.Contains("trackpad") ? "trackpad" : "joystick",
            _ => "button",
        };

        return (source, component, mode);
    }
}
