using Valve.VR;

namespace FloatSoda.OVR;

// ReSharper disable once InconsistentNaming
public class EVRInitializeException(string message, EVRInitError errorCode) : OVRException<EVRInitError>(message, errorCode);

public static class VrInitialExceptionValidator
{
    public static void ThrowIfError(this EVRInitError error)
    {
        if (error == EVRInitError.None) return;

        throw error switch
        {
            // --- 一般的な初期化エラー ---
            EVRInitError.Unknown => new EVRInitializeException("未知の初期化エラーが発生しました。", error),
            EVRInitError.Init_InstallationNotFound => new EVRInitializeException("OpenVRのインストールが見つかりません。", error),
            EVRInitError.Init_InstallationCorrupt => new EVRInitializeException("OpenVRのインストールが壊れています。", error),
            EVRInitError.Init_VRClientDLLNotFound => new EVRInitializeException("vrclient.dllが見つかりません。", error),
            EVRInitError.Init_FileNotFound => new EVRInitializeException("必要な構成ファイルが見つかりません。", error),
            EVRInitError.Init_FactoryNotFound => new EVRInitializeException("ファクトリインターフェースの取得に失敗しました。", error),
            EVRInitError.Init_InterfaceNotFound => new EVRInitializeException("要求されたインターフェースが見つかりません。", error),
            EVRInitError.Init_InvalidInterface => new EVRInitializeException("インターフェースが無効です。", error),
            EVRInitError.Init_UserConfigDirectoryInvalid => new EVRInitializeException("ユーザー設定ディレクトリが無効です。", error),
            EVRInitError.Init_HmdNotFound => new EVRInitializeException("HMDが見つからないか、接続されていません。", error),
            EVRInitError.Init_NotInitialized => new EVRInitializeException("OpenVRが初期化されていません。", error),
            EVRInitError.Init_PathRegistryNotFound => new EVRInitializeException("パスレジストリが見つかりません。", error),
            EVRInitError.Init_NoConfigPath => new EVRInitializeException("構成パスが設定されていません。", error),
            EVRInitError.Init_NoLogPath => new EVRInitializeException("ログパスが設定されていません。", error),
            EVRInitError.Init_PathRegistryNotWritable => new EVRInitializeException("パスレジストリに書き込めません。", error),
            EVRInitError.Init_AppInfoInitFailed => new EVRInitializeException("アプリケーション情報の初期化に失敗しました。", error),
            EVRInitError.Init_Retry => new EVRInitializeException("再試行が必要です。", error),
            EVRInitError.Init_InitCanceledByUser => new EVRInitializeException("ユーザーによって初期化がキャンセルされました。", error),
            EVRInitError.Init_AnotherAppLaunching => new EVRInitializeException("別のアプリケーションが起動中です。", error),
            EVRInitError.Init_SettingsInitFailed => new EVRInitializeException("設定の初期化に失敗しました。", error),
            EVRInitError.Init_ShuttingDown => new EVRInitializeException("システムが終了処理中です。", error),
            EVRInitError.Init_TooManyObjects => new EVRInitializeException("オブジェクトが多すぎます。", error),
            EVRInitError.Init_NoServerForBackgroundApp => new EVRInitializeException("バックグラウンドアプリ用のサーバーがありません。", error),
            EVRInitError.Init_NotSupportedWithCompositor => new EVRInitializeException("コンポジター使用時はサポートされません。", error),
            EVRInitError.Init_NotAvailableToUtilityApps => new EVRInitializeException("ユーティリティアプリでは利用できません。", error),
            EVRInitError.Init_Internal => new EVRInitializeException("内部エラーが発生しました。", error),
            EVRInitError.Init_HmdDriverIdIsNone => new EVRInitializeException("HMDドライバIDがNoneです。", error),
            EVRInitError.Init_HmdNotFoundPresenceFailed => new EVRInitializeException("HMDの存在確認に失敗しました。", error),
            EVRInitError.Init_VRMonitorNotFound => new EVRInitializeException("VRモニターが見つかりません。", error),
            EVRInitError.Init_VRMonitorStartupFailed => new EVRInitializeException("VRモニターの起動に失敗しました。", error),
            EVRInitError.Init_LowPowerWatchdogNotSupported => new EVRInitializeException("低電力ウォッチドッグはサポートされていません。", error),
            EVRInitError.Init_InvalidApplicationType => new EVRInitializeException("アプリケーションタイプが無効です。", error),
            EVRInitError.Init_NotAvailableToWatchdogApps => new EVRInitializeException("ウォッチドッグアプリでは利用できません。", error),
            EVRInitError.Init_WatchdogDisabledInSettings => new EVRInitializeException("設定でウォッチドッグが無効になっています。", error),
            EVRInitError.Init_VRDashboardNotFound => new EVRInitializeException("VRダッシュボードが見つかりません。", error),
            EVRInitError.Init_VRDashboardStartupFailed => new EVRInitializeException("VRダッシュボードの起動に失敗しました。", error),
            EVRInitError.Init_VRHomeNotFound => new EVRInitializeException("VR Homeが見つかりません。", error),
            EVRInitError.Init_VRHomeStartupFailed => new EVRInitializeException("VR Homeの起動に失敗しました。", error),
            EVRInitError.Init_RebootingBusy => new EVRInitializeException("再起動処理中のためビジーです。", error),
            EVRInitError.Init_FirmwareUpdateBusy => new EVRInitializeException("ファームウェア更新中のためビジーです。", error),
            EVRInitError.Init_FirmwareRecoveryBusy => new EVRInitializeException("ファームウェア復旧中のためビジーです。", error),
            EVRInitError.Init_USBServiceBusy => new EVRInitializeException("USBサービスがビジーです。", error),
            EVRInitError.Init_VRWebHelperStartupFailed => new EVRInitializeException("VR Web Helperの起動に失敗しました。", error),
            EVRInitError.Init_TrackerManagerInitFailed => new EVRInitializeException("トラッカーマネージャーの初期化に失敗しました。", error),
            EVRInitError.Init_AlreadyRunning => new EVRInitializeException("既に実行中です。", error),
            EVRInitError.Init_FailedForVrMonitor => new EVRInitializeException("VRモニター用プロセスの初期化に失敗しました。", error),
            EVRInitError.Init_PropertyManagerInitFailed => new EVRInitializeException("プロパティマネージャーの初期化に失敗しました。", error),
            EVRInitError.Init_WebServerFailed => new EVRInitializeException("Webサーバーの起動に失敗しました。", error),
            EVRInitError.Init_IllegalTypeTransition => new EVRInitializeException("不正なタイプ遷移です。", error),
            EVRInitError.Init_MismatchedRuntimes => new EVRInitializeException("ランタイムのバージョンが一致しません。", error),
            EVRInitError.Init_InvalidProcessId => new EVRInitializeException("プロセスIDが無効です。", error),
            EVRInitError.Init_VRServiceStartupFailed => new EVRInitializeException("VRサービスの起動に失敗しました。", error),
            EVRInitError.Init_PrismNeedsNewDrivers => new EVRInitializeException("Prismドライバの更新が必要です。", error),
            EVRInitError.Init_PrismStartupTimedOut => new EVRInitializeException("Prismの起動がタイムアウトしました。", error),
            EVRInitError.Init_CouldNotStartPrism => new EVRInitializeException("Prismを起動できませんでした。", error),
            EVRInitError.Init_CreateDriverDirectDeviceFailed => new EVRInitializeException("ドライバダイレクトデバイスの作成に失敗しました。", error),
            EVRInitError.Init_PrismExitedUnexpectedly => new EVRInitializeException("Prismが予期せず終了しました。", error),

            // --- ドライバ関連 ---
            EVRInitError.Driver_Failed => new EVRInitializeException("ドライバのエラーです。", error),
            EVRInitError.Driver_Unknown => new EVRInitializeException("未知のドライバエラーです。", error),
            EVRInitError.Driver_HmdUnknown => new EVRInitializeException("未知のHMDドライバです。", error),
            EVRInitError.Driver_NotLoaded => new EVRInitializeException("ドライバがロードされていません。", error),
            EVRInitError.Driver_RuntimeOutOfDate => new EVRInitializeException("ドライバのランタイムが古すぎます。", error),
            EVRInitError.Driver_HmdInUse => new EVRInitializeException("HMDが別のプロセスで使用中です。", error),
            EVRInitError.Driver_NotCalibrated => new EVRInitializeException("ドライバが校正されていません。", error),
            EVRInitError.Driver_CalibrationInvalid => new EVRInitializeException("ドライバの校正データが無効です。", error),
            EVRInitError.Driver_HmdDisplayNotFound => new EVRInitializeException("HMDのディスプレイが見つかりません。", error),
            EVRInitError.Driver_TrackedDeviceInterfaceUnknown => new EVRInitializeException("トラッキングデバイスインターフェースが不明です。", error),
            EVRInitError.Driver_HmdDriverIdOutOfBounds => new EVRInitializeException("HMDドライバIDが範囲外です。", error),
            EVRInitError.Driver_HmdDisplayMirrored => new EVRInitializeException("HMDディスプレイがミラーリング設定になっています。", error),
            EVRInitError.Driver_HmdDisplayNotFoundLaptop => new EVRInitializeException("ラップトップ用HMDディスプレイが見つかりません。", error),

            // --- IPC (プロセス間通信) 関連 ---
            EVRInitError.IPC_ServerInitFailed => new EVRInitializeException("IPCサーバーの初期化に失敗しました。", error),
            EVRInitError.IPC_ConnectFailed => new EVRInitializeException("IPC接続に失敗しました。", error),
            EVRInitError.IPC_SharedStateInitFailed => new EVRInitializeException("共有ステートの初期化に失敗しました。", error),
            EVRInitError.IPC_CompositorInitFailed => new EVRInitializeException("コンポジターの初期化に失敗しました。", error),
            EVRInitError.IPC_MutexInitFailed => new EVRInitializeException("Mutexの初期化に失敗しました。", error),
            EVRInitError.IPC_Failed => new EVRInitializeException("IPC接続エラーが発生しました。", error),
            EVRInitError.IPC_CompositorConnectFailed => new EVRInitializeException("コンポジターへの接続に失敗しました。", error),
            EVRInitError.IPC_CompositorInvalidConnectResponse => new EVRInitializeException("コンポジターからの接続レスポンスが無効です。", error),
            EVRInitError.IPC_ConnectFailedAfterMultipleAttempts => new EVRInitializeException("複数回の試行後、IPC接続に失敗しました。", error),
            EVRInitError.IPC_ConnectFailedAfterTargetExited => new EVRInitializeException("ターゲット終了後、IPC接続に失敗しました。", error),
            EVRInitError.IPC_NamespaceUnavailable => new EVRInitializeException("IPCネームスペースを利用できません。", error),

            // --- コンポジター関連 ---
            EVRInitError.Compositor_Failed => new EVRInitializeException("コンポジターが失敗しました。", error),
            EVRInitError.Compositor_D3D11HardwareRequired => new EVRInitializeException("Direct3D11ハードウェアが必要です。", error),
            EVRInitError.Compositor_FirmwareRequiresUpdate => new EVRInitializeException("コンポジター用にファームウェアの更新が必要です。", error),
            EVRInitError.Compositor_OverlayInitFailed => new EVRInitializeException("コンポジターオーバーレイの初期化に失敗しました。", error),
            EVRInitError.Compositor_ScreenshotsInitFailed => new EVRInitializeException("コンポジタースクリーンショットの初期化に失敗しました。", error),
            EVRInitError.Compositor_UnableToCreateDevice => new EVRInitializeException("グラフィックスデバイスを作成できませんでした。", error),
            EVRInitError.Compositor_SharedStateIsNull => new EVRInitializeException("共有ステートがnullです。", error),
            EVRInitError.Compositor_NotificationManagerIsNull => new EVRInitializeException("通知マネージャーがnullです。", error),
            EVRInitError.Compositor_ResourceManagerClientIsNull => new EVRInitializeException("リソースマネージャークライアントがnullです。", error),
            EVRInitError.Compositor_MessageOverlaySharedStateInitFailure => new EVRInitializeException("メッセージオーバーレイ共有ステートの初期化に失敗しました。", error),
            EVRInitError.Compositor_PropertiesInterfaceIsNull => new EVRInitializeException("プロパティインターフェースがnullです。", error),
            EVRInitError.Compositor_CreateFullscreenWindowFailed => new EVRInitializeException("全画面ウィンドウの作成に失敗しました。", error),
            EVRInitError.Compositor_SettingsInterfaceIsNull => new EVRInitializeException("設定インターフェースがnullです。", error),
            EVRInitError.Compositor_FailedToShowWindow => new EVRInitializeException("ウィンドウの表示に失敗しました。", error),
            EVRInitError.Compositor_DistortInterfaceIsNull => new EVRInitializeException("歪み補正インターフェースがnullです。", error),
            EVRInitError.Compositor_DisplayFrequencyFailure => new EVRInitializeException("ディスプレイ周波数の取得に失敗しました。", error),
            EVRInitError.Compositor_RendererInitializationFailed => new EVRInitializeException("レンダラーの初期化に失敗しました。", error),
            EVRInitError.Compositor_DXGIFactoryInterfaceIsNull => new EVRInitializeException("DXGIファクトリインターフェースがnullです。", error),
            EVRInitError.Compositor_DXGIFactoryCreateFailed => new EVRInitializeException("DXGIファクトリの作成に失敗しました。", error),
            EVRInitError.Compositor_DXGIFactoryQueryFailed => new EVRInitializeException("DXGIファクトリのクエリに失敗しました。", error),
            EVRInitError.Compositor_InvalidAdapterDesktop => new EVRInitializeException("デスクトップアダプターが無効です。", error),
            EVRInitError.Compositor_InvalidHmdAttachment => new EVRInitializeException("HMDの接続が無効です。", error),
            EVRInitError.Compositor_InvalidOutputDesktop => new EVRInitializeException("出力デスクトップが無効です。", error),
            EVRInitError.Compositor_InvalidDeviceProvided => new EVRInitializeException("提供されたデバイスが無効です。", error),
            EVRInitError.Compositor_D3D11RendererInitializationFailed => new EVRInitializeException("D3D11レンダラーの初期化に失敗しました。", error),
            EVRInitError.Compositor_FailedToFindDisplayMode => new EVRInitializeException("ディスプレイモードが見つかりませんでした。", error),
            EVRInitError.Compositor_FailedToCreateSwapChain => new EVRInitializeException("スワップチェーンの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToGetBackBuffer => new EVRInitializeException("バックバッファの取得に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateRenderTarget => new EVRInitializeException("レンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDXGI2SwapChain => new EVRInitializeException("DXGI2スワップチェーンの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedtoGetDXGI2BackBuffer => new EVRInitializeException("DXGI2バックバッファの取得に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDXGI2RenderTarget => new EVRInitializeException("DXGI2レンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToGetDXGIDeviceInterface => new EVRInitializeException("DXGIデバイスインターフェースの取得に失敗しました。", error),
            EVRInitError.Compositor_SelectDisplayMode => new EVRInitializeException("ディスプレイモードの選択に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateNvAPIRenderTargets => new EVRInitializeException("NvAPIレンダーターゲットの作成に失敗しました。", error),
            EVRInitError.Compositor_NvAPISetDisplayMode => new EVRInitializeException("NvAPIディスプレイモード設定に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateDirectModeDisplay => new EVRInitializeException("ダイレクトモードディスプレイの作成に失敗しました。", error),
            EVRInitError.Compositor_InvalidHmdPropertyContainer => new EVRInitializeException("HMDプロパティコンテナが無効です。", error),
            EVRInitError.Compositor_UpdateDisplayFrequency => new EVRInitializeException("ディスプレイ周波数の更新に失敗しました。", error),
            EVRInitError.Compositor_CreateRasterizerState => new EVRInitializeException("ラスタライザステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateWireframeRasterizerState => new EVRInitializeException("ワイヤーフレームラスタライザステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSamplerState => new EVRInitializeException("サンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateClampToBorderSamplerState => new EVRInitializeException("ClampToBorderサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateAnisoSamplerState => new EVRInitializeException("異方性サンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlaySamplerState => new EVRInitializeException("オーバーレイサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePanoramaSamplerState => new EVRInitializeException("パノラマサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateFontSamplerState => new EVRInitializeException("フォントサンプラーステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateNoBlendState => new EVRInitializeException("NoBlendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendState => new EVRInitializeException("Blendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateAlphaBlendState => new EVRInitializeException("AlphaBlendステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskR => new EVRInitializeException("BlendStateMaskRの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskG => new EVRInitializeException("BlendStateMaskGの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateBlendStateMaskB => new EVRInitializeException("BlendStateMaskBの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilState => new EVRInitializeException("深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilStateNoWrite => new EVRInitializeException("NoWrite深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDepthStencilStateNoDepth => new EVRInitializeException("NoDepth深度ステンシルステートの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateFlushTexture => new EVRInitializeException("Flushテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDistortionSurfaces => new EVRInitializeException("歪み補正サーフェスの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateConstantBuffer => new EVRInitializeException("定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateHmdPoseConstantBuffer => new EVRInitializeException("HMDポーズ定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateHmdPoseStagingConstantBuffer => new EVRInitializeException("HMDポーズステージングバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSharedFrameInfoConstantBuffer => new EVRInitializeException("フレーム情報共有バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayConstantBuffer => new EVRInitializeException("オーバーレイ定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateSceneTextureIndexConstantBuffer => new EVRInitializeException("シーンテクスチャインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateReadableSceneTextureIndexConstantBuffer => new EVRInitializeException("読み取り可能シーンテクスチャインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerGraphicsTextureIndexConstantBuffer => new EVRInitializeException("レイヤーグラフィックスインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerComputeTextureIndexConstantBuffer => new EVRInitializeException("レイヤー演算インデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLayerComputeSceneTextureIndexConstantBuffer => new EVRInitializeException("レイヤー演算シーンインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateComputeHmdPoseConstantBuffer => new EVRInitializeException("演算用HMDポーズバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateGeomConstantBuffer => new EVRInitializeException("幾何定数バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePanelMaskConstantBuffer => new EVRInitializeException("パネルマスクバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreatePixelSimUBO => new EVRInitializeException("PixelSimUBOの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMSAARenderTextures => new EVRInitializeException("MSAAレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateResolveRenderTextures => new EVRInitializeException("Resolveレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateComputeResolveRenderTextures => new EVRInitializeException("演算用Resolveレンダーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateDriverDirectModeResolveTextures => new EVRInitializeException("ドライバダイレクトResolveテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_OpenDriverDirectModeResolveTextures => new EVRInitializeException("ドライバダイレクトResolveテクスチャを開けませんでした。", error),
            EVRInitError.Compositor_CreateFallbackSyncTexture => new EVRInitializeException("フォールバック同期テクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_ShareFallbackSyncTexture => new EVRInitializeException("フォールバック同期テクスチャの共有に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayIndexBuffer => new EVRInitializeException("オーバーレイインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateOverlayVertexBuffer => new EVRInitializeException("オーバーレイ頂点バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateTextVertexBuffer => new EVRInitializeException("テキスト頂点バッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateTextIndexBuffer => new EVRInitializeException("テキストインデックスバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMirrorTextures => new EVRInitializeException("ミラーテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateLastFrameRenderTexture => new EVRInitializeException("直前フレームレンダリングテクスチャの作成に失敗しました。", error),
            EVRInitError.Compositor_CreateMirrorOverlay => new EVRInitializeException("ミラーオーバーレイの作成に失敗しました。", error),
            EVRInitError.Compositor_FailedToCreateVirtualDisplayBackbuffer => new EVRInitializeException("仮想ディスプレイバックバッファの作成に失敗しました。", error),
            EVRInitError.Compositor_DisplayModeNotSupported => new EVRInitializeException("ディスプレイモードがサポートされていません。", error),
            EVRInitError.Compositor_CreateOverlayInvalidCall => new EVRInitializeException("オーバーレイ作成呼び出しが無効です。", error),
            EVRInitError.Compositor_CreateOverlayAlreadyInitialized => new EVRInitializeException("オーバーレイは既に初期化されています。", error),
            EVRInitError.Compositor_FailedToCreateMailbox => new EVRInitializeException("メールボックスの作成に失敗しました。", error),
            EVRInitError.Compositor_WindowInterfaceIsNull => new EVRInitializeException("ウィンドウインターフェースがnullです。", error),
            EVRInitError.Compositor_SystemLayerCreateInstance => new EVRInitializeException("システムレイヤーインスタンスの作成に失敗しました。", error),
            EVRInitError.Compositor_SystemLayerCreateSession => new EVRInitializeException("システムレイヤーセッションの作成に失敗しました。", error),

            // --- ベンダー固有エラー (Oculus/Meta等) ---
            EVRInitError.VendorSpecific_UnableToConnectToOculusRuntime => new EVRInitializeException("Oculusランタイムに接続できません。", error),
            EVRInitError.VendorSpecific_WindowsNotInDevMode => new EVRInitializeException("Windowsが開発者モードではありません。", error),
            EVRInitError.VendorSpecific_HmdFound_CantOpenDevice => new EVRInitializeException("HMDデバイスを開けませんでした。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToRequestConfigStart => new EVRInitializeException("HMD構成開始の要求に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_NoStoredConfig => new EVRInitializeException("HMD内に保存された構成がありません。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigTooBig => new EVRInitializeException("HMD構成データが大きすぎます。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigTooSmall => new EVRInitializeException("HMD構成データが小さすぎます。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToInitZLib => new EVRInitializeException("zlibの初期化に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_CantReadFirmwareVersion => new EVRInitializeException("ファームウェアバージョンの読み取りに失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToSendUserDataStart => new EVRInitializeException("ユーザーデータ送信開始に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToGetUserDataStart => new EVRInitializeException("ユーザーデータ取得開始に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UnableToGetUserDataNext => new EVRInitializeException("ユーザーデータ次フレーム取得に失敗しました。", error),
            EVRInitError.VendorSpecific_HmdFound_UserDataAddressRange => new EVRInitializeException("ユーザーデータのアドレス範囲エラーです。", error),
            EVRInitError.VendorSpecific_HmdFound_UserDataError => new EVRInitializeException("ユーザーデータエラーが発生しました。", error),
            EVRInitError.VendorSpecific_HmdFound_ConfigFailedSanityCheck => new EVRInitializeException("HMD構成データの整合性チェックに失敗しました。", error),
            EVRInitError.VendorSpecific_OculusRuntimeBadInstall => new EVRInitializeException("Oculusランタイムのインストールが不完全です。", error),

            // --- その他 ---
            EVRInitError.Steam_SteamInstallationNotFound => new EVRInitializeException("Steamのインストールが見つかりません。", error),
            EVRInitError.LastError => new EVRInitializeException("最後のエラーが発生しました。", error),

            _ => throw new ArgumentOutOfRangeException(nameof(error), error, $"予期しない初期化エラーが発生しました: {error}")
        };
    }
}